//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_HVR : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Single LeftGrip
        {
            get
            {
                return SteamVR_Actions.hVR_LeftGrip;
            }
        }
        
        public virtual SteamVR_Action_Single LeftTrigger
        {
            get
            {
                return SteamVR_Actions.hVR_LeftTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftPrimary
        {
            get
            {
                return SteamVR_Actions.hVR_LeftPrimary;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftPrimaryTouch
        {
            get
            {
                return SteamVR_Actions.hVR_LeftPrimaryTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftSecondary
        {
            get
            {
                return SteamVR_Actions.hVR_LeftSecondary;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftSecondaryTouch
        {
            get
            {
                return SteamVR_Actions.hVR_LeftSecondaryTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftMenu
        {
            get
            {
                return SteamVR_Actions.hVR_LeftMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftPrimaryAxisClick
        {
            get
            {
                return SteamVR_Actions.hVR_LeftPrimaryAxisClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftSecondaryAxisClick
        {
            get
            {
                return SteamVR_Actions.hVR_LeftSecondaryAxisClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftPrimaryAxisTouch
        {
            get
            {
                return SteamVR_Actions.hVR_LeftPrimaryAxisTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftTriggerTouch
        {
            get
            {
                return SteamVR_Actions.hVR_LeftTriggerTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftThumbTouch
        {
            get
            {
                return SteamVR_Actions.hVR_LeftThumbTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftTriggerNearTouch
        {
            get
            {
                return SteamVR_Actions.hVR_LeftTriggerNearTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftThumbNearTouch
        {
            get
            {
                return SteamVR_Actions.hVR_LeftThumbNearTouch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 LeftPrimaryAxis
        {
            get
            {
                return SteamVR_Actions.hVR_LeftPrimaryAxis;
            }
        }
        
        public virtual SteamVR_Action_Vector2 LeftSecondaryAxis
        {
            get
            {
                return SteamVR_Actions.hVR_LeftSecondaryAxis;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftSecondaryAxisTouch
        {
            get
            {
                return SteamVR_Actions.hVR_LeftSecondaryAxisTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftGripButton
        {
            get
            {
                return SteamVR_Actions.hVR_LeftGripButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftTriggerButton
        {
            get
            {
                return SteamVR_Actions.hVR_LeftTriggerButton;
            }
        }
        
        public virtual SteamVR_Action_Single RightGrip
        {
            get
            {
                return SteamVR_Actions.hVR_RightGrip;
            }
        }
        
        public virtual SteamVR_Action_Single RightTrigger
        {
            get
            {
                return SteamVR_Actions.hVR_RightTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightPrimary
        {
            get
            {
                return SteamVR_Actions.hVR_RightPrimary;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightPrimaryTouch
        {
            get
            {
                return SteamVR_Actions.hVR_RightPrimaryTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightSecondary
        {
            get
            {
                return SteamVR_Actions.hVR_RightSecondary;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightSecondaryTouch
        {
            get
            {
                return SteamVR_Actions.hVR_RightSecondaryTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightMenu
        {
            get
            {
                return SteamVR_Actions.hVR_RightMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightPrimaryAxisClick
        {
            get
            {
                return SteamVR_Actions.hVR_RightPrimaryAxisClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightSecondaryAxisClick
        {
            get
            {
                return SteamVR_Actions.hVR_RightSecondaryAxisClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightPrimaryAxisTouch
        {
            get
            {
                return SteamVR_Actions.hVR_RightPrimaryAxisTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightTriggerTouch
        {
            get
            {
                return SteamVR_Actions.hVR_RightTriggerTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightThumbTouch
        {
            get
            {
                return SteamVR_Actions.hVR_RightThumbTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightTriggerNearTouch
        {
            get
            {
                return SteamVR_Actions.hVR_RightTriggerNearTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightThumbNearTouch
        {
            get
            {
                return SteamVR_Actions.hVR_RightThumbNearTouch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 RightPrimaryAxis
        {
            get
            {
                return SteamVR_Actions.hVR_RightPrimaryAxis;
            }
        }
        
        public virtual SteamVR_Action_Vector2 RightSecondaryAxis
        {
            get
            {
                return SteamVR_Actions.hVR_RightSecondaryAxis;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightSecondaryAxisTouch
        {
            get
            {
                return SteamVR_Actions.hVR_RightSecondaryAxisTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightGripButton
        {
            get
            {
                return SteamVR_Actions.hVR_RightGripButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightTriggerButton
        {
            get
            {
                return SteamVR_Actions.hVR_RightTriggerButton;
            }
        }
        
        public virtual SteamVR_Action_Skeleton left_skeleton
        {
            get
            {
                return SteamVR_Actions.hVR_left_skeleton;
            }
        }
        
        public virtual SteamVR_Action_Skeleton right_skeleton
        {
            get
            {
                return SteamVR_Actions.hVR_right_skeleton;
            }
        }
        
        public virtual SteamVR_Action_Single LeftGripForce
        {
            get
            {
                return SteamVR_Actions.hVR_LeftGripForce;
            }
        }
        
        public virtual SteamVR_Action_Single RightGripForce
        {
            get
            {
                return SteamVR_Actions.hVR_RightGripForce;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptics
        {
            get
            {
                return SteamVR_Actions.hVR_Haptics;
            }
        }
        
        public virtual SteamVR_Action_Vibration RightHaptics
        {
            get
            {
                return SteamVR_Actions.hVR_RightHaptics;
            }
        }
    }
}
